# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: 홈페이지
    url: /
    weight: 10
  - name: 이력내용
    url: about/
    weight: 20
  - name: 우리학교 커리큘럼
    url: myschool/
    weight: 30
  - name: 내가 배운 것들
    url: study/
    weight: 40
  - name: 나에 대하여
    url: me/
    weight: 50
  - name: 연락처
    url: me/contact/
    parent: 나에 대하여
    weight: 1
  - name: 블로그
    url: me/blog/
    parent: 나에 대하여
    weight: 2
